import { describe, it, expect } from 'vitest';
import { financeService } from './finance.service';

describe('financeService — Accounts', () => {
  it('ALLOW: listAccounts returns only accounts of the requesting tenant', async () => {
    const result = await financeService.listAccounts('T-001');
    expect(result.every((account) => account.tenantId === 'T-001')).toBe(true);
    expect(result.length).toBeGreaterThan(0);
  });

  it('DENY: getAccount returns null for an account of another tenant', async () => {
    const [t001Accounts, t002Accounts] = await Promise.all([financeService.listAccounts('T-001'), financeService.listAccounts('T-002')]);
    expect(t002Accounts.length).toBeGreaterThan(0);
    const otherTenantAccountId = t002Accounts[0].id;
    const result = await financeService.getAccount('T-001', otherTenantAccountId);
    expect(result).toBeNull();
    expect(t001Accounts.some((account) => account.id === otherTenantAccountId)).toBe(false);
  });

  it('ALLOW: getAccount returns the account when it belongs to the requesting tenant', async () => {
    const [account] = await financeService.listAccounts('T-001');
    const result = await financeService.getAccount('T-001', account.id);
    expect(result?.id).toBe(account.id);
  });
});

describe('financeService — createAccount (caisse)', () => {
  it('ALLOW: creates a LIBRE account without an amount', async () => {
    const account = await financeService.createAccount('T-001', 'Coopérative Sutura', { title: `Epargne libre ${Date.now()}`, type: 'LIBRE', amount: null, description: 'Epargne volontaire des adhérents' });
    expect(account).toBeTruthy();
    expect(account?.type).toBe('LIBRE');
    expect(account?.amount).toBeNull();
  });

  it('ALLOW: creates a TAUX_FIXE account with a fixed amount', async () => {
    const account = await financeService.createAccount('T-001', 'Coopérative Sutura', { title: `Inscription ${Date.now()}`, type: 'TAUX_FIXE', amount: 500, description: "Cotisation d'inscription" });
    expect(account).toBeTruthy();
    expect(account?.type).toBe('TAUX_FIXE');
    expect(account?.amount).toBe(500);
  });

  it('DENY: rejects a TAUX_FIXE account without an amount', async () => {
    const account = await financeService.createAccount('T-001', 'Coopérative Sutura', { title: `Secours ${Date.now()}`, type: 'TAUX_FIXE', amount: null, description: '' });
    expect(account).toBeNull();
  });

  it('DENY: rejects a TAUX_FIXE account with a negative amount', async () => {
    const account = await financeService.createAccount('T-001', 'Coopérative Sutura', { title: `Négatif ${Date.now()}`, type: 'TAUX_FIXE', amount: -100, description: '' });
    expect(account).toBeNull();
  });

  it('DENY: rejects a TAUX_FIXE account with an amount of exactly 0 (must be strictly positive)', async () => {
    const account = await financeService.createAccount('T-001', 'Coopérative Sutura', { title: `Zéro ${Date.now()}`, type: 'TAUX_FIXE', amount: 0, description: '' });
    expect(account).toBeNull();
  });

  it('DENY: rejects an unknown account type', async () => {
    // @ts-expect-error — runtime guard test for a value TypeScript would otherwise reject at compile time.
    const account = await financeService.createAccount('T-001', 'Coopérative Sutura', { title: `Inconnu ${Date.now()}`, type: 'ASSET', amount: null, description: '' });
    expect(account).toBeNull();
  });

  it('DENY: rejects a duplicate title within the same tenant', async () => {
    const title = `Doublon ${Date.now()}`;
    const first = await financeService.createAccount('T-001', 'Coopérative Sutura', { title, type: 'LIBRE', amount: null, description: '' });
    expect(first).toBeTruthy();
    const second = await financeService.createAccount('T-001', 'Coopérative Sutura', { title, type: 'LIBRE', amount: null, description: '' });
    expect(second).toBeNull();
  });

  it('ALLOW: the same title is allowed again in a different tenant', async () => {
    const title = `Multi-tenant ${Date.now()}`;
    const t001Account = await financeService.createAccount('T-001', 'Coopérative Sutura', { title, type: 'LIBRE', amount: null, description: '' });
    const t002Account = await financeService.createAccount('T-002', 'Tontine Horizon', { title, type: 'LIBRE', amount: null, description: '' });
    expect(t001Account).toBeTruthy();
    expect(t002Account).toBeTruthy();
  });

  it('ISOLATION: tenantId is always taken from the service parameter, never from the input body', async () => {
    // AccountCreateInput has no `tenantId` field at the type level — this proves the created account is scoped to the tenant passed explicitly.
    const account = await financeService.createAccount('T-002', 'Tontine Horizon', { title: `Scopé ${Date.now()}`, type: 'LIBRE', amount: null, description: '' });
    expect(account?.tenantId).toBe('T-002');
    expect(account?.tenantName).toBe('Tontine Horizon');
  });

  it('AUTO: accountNumber is always generated by the service, never supplied by the caller', async () => {
    const account = await financeService.createAccount('T-001', 'Coopérative Sutura', { title: `Auto n° ${Date.now()}`, type: 'LIBRE', amount: null, description: '' });
    expect(account?.accountNumber).toBeTruthy();
    expect(account?.status).toBe('active');
    expect(account?.balance).toBe(0);
  });
});

describe('financeService — updateAccount', () => {
  it('ALLOW: updates title/type/amount/description for the owning tenant', async () => {
    const created = await financeService.createAccount('T-001', 'Coopérative Sutura', { title: `À modifier ${Date.now()}`, type: 'LIBRE', amount: null, description: '' });
    const updated = await financeService.updateAccount('T-001', created!.id, { type: 'TAUX_FIXE', amount: 1000 });
    expect(updated?.type).toBe('TAUX_FIXE');
    expect(updated?.amount).toBe(1000);
  });

  it('DENY: cannot update an account of another tenant', async () => {
    const created = await financeService.createAccount('T-001', 'Coopérative Sutura', { title: `Isolé ${Date.now()}`, type: 'LIBRE', amount: null, description: '' });
    const result = await financeService.updateAccount('T-002', created!.id, { title: 'Piraté' });
    expect(result).toBeNull();
  });

  it('DENY: switching to TAUX_FIXE without providing an amount is rejected', async () => {
    const created = await financeService.createAccount('T-001', 'Coopérative Sutura', { title: `Sans montant ${Date.now()}`, type: 'LIBRE', amount: null, description: '' });
    const result = await financeService.updateAccount('T-001', created!.id, { type: 'TAUX_FIXE' });
    expect(result).toBeNull();
  });

  it('DENY: switching to TAUX_FIXE with an amount of exactly 0 is rejected', async () => {
    const created = await financeService.createAccount('T-001', 'Coopérative Sutura', { title: `Zéro modif ${Date.now()}`, type: 'LIBRE', amount: null, description: '' });
    const result = await financeService.updateAccount('T-001', created!.id, { type: 'TAUX_FIXE', amount: 0 });
    expect(result).toBeNull();
  });

  it('SAFE: updateAccount never mutates balance or accountNumber', async () => {
    const created = await financeService.createAccount('T-001', 'Coopérative Sutura', { title: `Intégrité technique ${Date.now()}`, type: 'LIBRE', amount: null, description: '' });
    const updated = await financeService.updateAccount('T-001', created!.id, { title: 'Renommée' });
    expect(updated?.balance).toBe(created!.balance);
    expect(updated?.accountNumber).toBe(created!.accountNumber);
  });
});

describe('financeService — deleteAccount', () => {
  it('ALLOW: deletes an account with no linked transactions', async () => {
    const created = await financeService.createAccount('T-001', 'Coopérative Sutura', { title: `Jetable ${Date.now()}`, type: 'LIBRE', amount: null, description: '' });
    const result = await financeService.deleteAccount('T-001', created!.id);
    expect(result?.deleted).toBe(true);
    const after = await financeService.getAccount('T-001', created!.id);
    expect(after).toBeNull();
  });

  it('SAFE: deactivates instead of deleting an account with existing movements', async () => {
    // AC-001 (CS-001-TRÉS) is referenced by seeded transactions (fromAccount/toAccount).
    const result = await financeService.deleteAccount('T-001', 'AC-001');
    expect(result?.deleted).toBe(false);
    expect(result?.deactivated).toBe(true);
    const after = await financeService.getAccount('T-001', 'AC-001');
    expect(after?.status).toBe('inactive');
  });
});

describe('financeService — account member assignment (adhésions à la caisse)', () => {
  it('ALLOW: adds a single member to an account', async () => {
    const created = await financeService.createAccount('T-001', 'Coopérative Sutura', { title: `Caisse membre unique ${Date.now()}`, type: 'LIBRE', amount: null, description: '' });
    const updated = await financeService.addAccountMembers('T-001', created!.id, ['M-001']);
    expect(updated?.memberIds).toContain('M-001');
  });

  it('ALLOW: adds several members at once', async () => {
    const created = await financeService.createAccount('T-001', 'Coopérative Sutura', { title: `Caisse plusieurs membres ${Date.now()}`, type: 'LIBRE', amount: null, description: '' });
    const updated = await financeService.addAccountMembers('T-001', created!.id, ['M-001', 'M-006']);
    expect(updated?.memberIds.sort()).toEqual(['M-001', 'M-006'].sort());
  });

  it('ALLOW: removes a single member', async () => {
    const created = await financeService.createAccount('T-001', 'Coopérative Sutura', { title: `Caisse retrait ${Date.now()}`, type: 'LIBRE', amount: null, description: '' });
    await financeService.addAccountMembers('T-001', created!.id, ['M-001', 'M-006']);
    const updated = await financeService.removeAccountMembers('T-001', created!.id, ['M-001']);
    expect(updated?.memberIds).toEqual(['M-006']);
  });

  it('ALLOW: removes all members', async () => {
    const created = await financeService.createAccount('T-001', 'Coopérative Sutura', { title: `Caisse retrait total ${Date.now()}`, type: 'LIBRE', amount: null, description: '' });
    await financeService.addAccountMembers('T-001', created!.id, ['M-001', 'M-006']);
    const updated = await financeService.removeAccountMembers('T-001', created!.id, ['M-001', 'M-006']);
    expect(updated?.memberIds).toEqual([]);
  });

  it('ISOLATION: a memberId from another tenant is silently ignored', async () => {
    const created = await financeService.createAccount('T-001', 'Coopérative Sutura', { title: `Caisse isolation ${Date.now()}`, type: 'LIBRE', amount: null, description: '' });
    const updated = await financeService.addAccountMembers('T-001', created!.id, ['M-001', 'M-002']); // M-002 belongs to T-002
    expect(updated?.memberIds).toEqual(['M-001']);
  });

  it('ISOLATION: cannot manage members of an account belonging to another tenant', async () => {
    const created = await financeService.createAccount('T-001', 'Coopérative Sutura', { title: `Caisse protégée ${Date.now()}`, type: 'LIBRE', amount: null, description: '' });
    const result = await financeService.addAccountMembers('T-002', created!.id, ['M-002']);
    expect(result).toBeNull();
  });

  it('SAFE: a non-existent memberId is silently ignored, no crash', async () => {
    const created = await financeService.createAccount('T-001', 'Coopérative Sutura', { title: `Caisse membre inexistant ${Date.now()}`, type: 'LIBRE', amount: null, description: '' });
    const updated = await financeService.addAccountMembers('T-001', created!.id, ['M-999-DOES-NOT-EXIST']);
    expect(updated?.memberIds).toEqual([]);
  });

  it('SAFE: adding the same member twice does not create a duplicate entry', async () => {
    const created = await financeService.createAccount('T-001', 'Coopérative Sutura', { title: `Caisse doublon membre ${Date.now()}`, type: 'LIBRE', amount: null, description: '' });
    await financeService.addAccountMembers('T-001', created!.id, ['M-001']);
    const updated = await financeService.addAccountMembers('T-001', created!.id, ['M-001']);
    expect(updated?.memberIds).toEqual(['M-001']);
  });

  it('listAccountMembers only returns members of the requesting tenant', async () => {
    const created = await financeService.createAccount('T-001', 'Coopérative Sutura', { title: `Caisse liste ${Date.now()}`, type: 'LIBRE', amount: null, description: '' });
    await financeService.addAccountMembers('T-001', created!.id, ['M-001']);
    const result = await financeService.listAccountMembers('T-001', created!.id);
    expect(result.every((member) => member.tenantId === 'T-001')).toBe(true);
    expect(result.map((member) => member.id)).toContain('M-001');
  });
});

describe('financeService — Transactions', () => {
  it('ALLOW/DENY: listTransactions is scoped to the requesting tenant', async () => {
    const [t001, t002] = await Promise.all([financeService.listTransactions('T-001'), financeService.listTransactions('T-002')]);
    expect(t001.every((transaction) => transaction.tenantId === 'T-001')).toBe(true);
    expect(t002.every((transaction) => transaction.tenantId === 'T-002')).toBe(true);
    const t002Ids = new Set(t002.map((transaction) => transaction.id));
    expect(t001.some((transaction) => t002Ids.has(transaction.id))).toBe(false);
  });
});

describe('financeService — Contributions', () => {
  it('ALLOW/DENY: listContributions is scoped to the requesting tenant', async () => {
    const [t001, t002] = await Promise.all([financeService.listContributions('T-001'), financeService.listContributions('T-002')]);
    expect(t001.every((contribution) => contribution.tenantId === 'T-001')).toBe(true);
    expect(t002.every((contribution) => contribution.tenantId === 'T-002')).toBe(true);
  });

  /**
   * GAP CONNU (non corrigé dans cette phase, additive-only) : contrairement à
   * tous les autres services, `listContributionsByMember` ne prend pas de
   * `tenantId` — aucune vérification possible au niveau service. Sûr
   * aujourd'hui uniquement parce que le seul point d'appel UI
   * (`organization-module.tsx`) obtient toujours `member.id` via
   * `organizationService.getMember(tenantId, memberId)`, déjà tenant-scopé
   * en amont — mais un appel direct au service avec un `memberId` d'un autre
   * tenant retournerait ses contributions sans aucun contrôle. Documenté ici
   * plutôt que corrigé silencieusement (voir docs/PHASE_12_INTEGRATION_TESTS_REGRESSION.md).
   */
  it('KNOWN GAP: listContributionsByMember has no tenant guard of its own (relies on caller pre-validation)', async () => {
    const result = await financeService.listContributionsByMember('M-002');
    expect(result.every((contribution) => contribution.memberId === 'M-002')).toBe(true);
  });
});

describe('financeService — Distributions', () => {
  it('ALLOW/DENY: listDistributions is scoped to the requesting tenant', async () => {
    const [t001, t002] = await Promise.all([financeService.listDistributions('T-001'), financeService.listDistributions('T-002')]);
    expect(t001.every((distribution) => distribution.tenantId === 'T-001')).toBe(true);
    expect(t002.every((distribution) => distribution.tenantId === 'T-002')).toBe(true);
  });

  it('DENY: approveDistribution cannot mutate a distribution of another tenant', async () => {
    const [distribution] = await financeService.listDistributions('T-001');
    const result = await financeService.approveDistribution('T-002', distribution.id);
    expect(result).toBeNull();
    const after = await financeService.listDistributions('T-001');
    expect(after.find((item) => item.id === distribution.id)?.status).toBe(distribution.status);
  });

  it('ALLOW: createDistribution attaches the correct tenantId regardless of caller', async () => {
    const distribution = await financeService.createDistribution('T-002', { beneficiary: 'Test', source: 'Test fund', amount: 1000, date: '2026-12-01' });
    expect(distribution.tenantId).toBe('T-002');
    expect(distribution.status).toBe('pending');
  });

  it('ALLOW: approveDistribution transitions status to completed for the owning tenant', async () => {
    const distribution = await financeService.createDistribution('T-001', { beneficiary: 'Test 2', source: 'Test fund', amount: 500, date: '2026-12-02' });
    const approved = await financeService.approveDistribution('T-001', distribution.id);
    expect(approved?.status).toBe('completed');
  });
});
