import { useMemo } from 'react';
import { useQuery } from '@tanstack/react-query';
import { ArrowDownRight, ArrowUpRight, BellRing, CalendarClock, ClipboardCheck, Clock3, Coins, CreditCard, HandCoins, Landmark, MoreHorizontal, ReceiptText, Sparkles, Users, WalletCards } from 'lucide-react';
import { Area, AreaChart, Bar, BarChart, CartesianGrid, Cell, Line, LineChart, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { useLocale } from '@/contexts/locale-context';
import { useTenant } from '@/contexts/tenant-context';
import { dashboardService, type DashboardOverview } from '@/services/dashboard.service';
import { queryKeys } from '@/services/query-keys';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Progress } from '@/components/ui/progress';
import { StatusBadge } from '@/components/status-badge';
import { EmptyState, CardSkeleton, ErrorState } from '@/components';
import { daysUntil, formatDate, formatNumber } from '@/lib/utils';
import { formatCurrency, getCurrencyDisplayLabel } from '@/constants/currencies';
import { useOrganizationCurrency } from '@/hooks/use-organization-currency';
import type { LucideIcon } from 'lucide-react';

type T = (section: 'dashboard' | 'notifications', key: string, values?: Record<string, string>) => string;
type KpiTone = 'info' | 'success' | 'warning' | 'neutral';

const chartColors = { blue: '#1b6bd1', blueLight: '#78b4f1', green: '#10b981', amber: '#f59e0b', rose: '#f43f5e', slate: '#94a3b8' };

function Panel({ title, icon: Icon, children, className = '', action }: { title: string; icon?: LucideIcon; children: React.ReactNode; className?: string; action?: React.ReactNode }) {
  return <Card className={`overflow-hidden border-border/80 shadow-sm transition-shadow duration-300 hover:shadow-md ${className}`}><CardHeader className="flex-row items-center justify-between gap-3 space-y-0 border-b border-border/60 px-5 py-4"><div className="flex min-w-0 items-center gap-2.5">{Icon && <span aria-hidden="true" className="grid size-8 shrink-0 place-items-center rounded-lg bg-primary/10 text-primary"><Icon size={16} /></span>}<CardTitle title={title} className="truncate text-sm font-semibold">{title}</CardTitle></div>{action}</CardHeader>{children}</Card>;
}

function ChartTooltipContent({ active, payload, label, money = true, currencyLabel = 'FCFA' }: { active?: boolean; payload?: Array<{ name?: string; value?: number; color?: string }>; label?: string; money?: boolean; currencyLabel?: string }) {
  if (!active || !payload?.length) return null;
  return <div className="rounded-lg border border-border bg-popover px-3 py-2 text-xs text-popover-foreground shadow-lg"><p className="mb-1.5 font-semibold">{label}</p>{payload.map((item) => <div key={item.name} className="flex items-center justify-between gap-5 py-0.5"><span className="flex items-center gap-1.5 text-muted-foreground"><span className="size-2 rounded-full" style={{ backgroundColor: item.color }} />{item.name}</span><span className="font-semibold">{money ? `${item.value?.toFixed(1)} M ${currencyLabel}` : formatNumber(item.value ?? 0)}</span></div>)}</div>;
}

function KpiCard({ label, value, delta, icon: Icon, tone = 'info' }: { label: string; value: string; delta: string; icon: LucideIcon; tone?: KpiTone }) {
  const hasDelta = Boolean(delta);
  const positive = delta.startsWith('+');
  const toneClass = tone === 'success' ? 'bg-emerald-500/10 text-emerald-600 dark:text-emerald-400' : tone === 'warning' ? 'bg-amber-500/10 text-amber-600 dark:text-amber-400' : tone === 'neutral' ? 'bg-muted text-muted-foreground' : 'bg-primary/10 text-primary';
  return <article className="group rounded-xl border border-border/80 bg-card p-4 shadow-sm transition-all duration-300 hover:-translate-y-0.5 hover:border-primary/30 hover:shadow-md"><div className="mb-4 flex items-center justify-between"><span className={`grid size-9 place-items-center rounded-lg ${toneClass}`}><Icon size={17} /></span>{hasDelta && <span className={`flex items-center gap-0.5 text-[11px] font-semibold ${positive ? 'text-emerald-600 dark:text-emerald-400' : 'text-rose-600 dark:text-rose-400'}`}>{positive ? <ArrowUpRight size={13} /> : <ArrowDownRight size={13} />}{delta}</span>}</div><p className="text-xs font-medium text-muted-foreground">{label}</p><p className="mt-1 font-heading text-[22px] font-semibold tracking-tight text-foreground">{value}</p></article>;
}

function KpiGrid({ t, locale, kpis }: { t: T; locale: 'fr' | 'en'; kpis: DashboardOverview['kpis'] }) {
  const currency = useOrganizationCurrency();
  const cards: Array<{ key: string; label: string; value: string; delta: string; icon: LucideIcon; tone: KpiTone }> = [
    { key: 'kpiMembers', label: t('dashboard', 'kpiMembers'), value: formatNumber(kpis.members.value, locale), delta: kpis.members.delta, icon: Users, tone: 'info' },
    { key: 'kpiTreasury', label: t('dashboard', 'kpiTreasury'), value: formatCurrency(kpis.treasury.value, currency, locale, { compact: true }), delta: kpis.treasury.delta, icon: Landmark, tone: 'success' },
    { key: 'kpiContributions', label: t('dashboard', 'kpiContributions'), value: formatCurrency(kpis.contributions.value, currency, locale, { compact: true }), delta: kpis.contributions.delta, icon: Coins, tone: 'info' },
    { key: 'kpiActiveLoans', label: t('dashboard', 'kpiActiveLoans'), value: formatNumber(kpis.activeLoans.value, locale), delta: kpis.activeLoans.delta, icon: CreditCard, tone: 'warning' },
    { key: 'kpiRepayments', label: t('dashboard', 'kpiRepayments'), value: formatCurrency(kpis.repayments.value, currency, locale, { compact: true }), delta: kpis.repayments.delta, icon: HandCoins, tone: 'success' },
    { key: 'kpiOutstanding', label: t('dashboard', 'kpiOutstanding'), value: formatCurrency(kpis.outstanding.value, currency, locale, { compact: true }), delta: kpis.outstanding.delta, icon: WalletCards, tone: 'warning' },
    { key: 'kpiActiveTontines', label: t('dashboard', 'kpiActiveTontines'), value: formatNumber(kpis.activeTontines.value, locale), delta: kpis.activeTontines.delta, icon: Coins, tone: 'info' },
    { key: 'kpiPendingWorkflows', label: t('dashboard', 'kpiPendingWorkflows'), value: formatNumber(kpis.pendingWorkflows.value, locale), delta: kpis.pendingWorkflows.delta, icon: ClipboardCheck, tone: 'warning' },
  ];
  return <section className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-5">{cards.map(({ key, ...kpi }) => <KpiCard key={key} {...kpi} />)}</section>;
}

function FinancialCharts({ t }: { t: T }) {
  const currencyLabel = getCurrencyDisplayLabel(useOrganizationCurrency());
  const overviewConfig = [{ key: 'treasury', label: t('dashboard', 'seriesTreasury'), color: chartColors.blue }, { key: 'contributions', label: t('dashboard', 'seriesContributions'), color: chartColors.green }, { key: 'repayments', label: t('dashboard', 'seriesRepayments'), color: chartColors.amber }];
  const { data: financialOverviewData = [] } = useQuery({ queryKey: queryKeys.dashboard.financialOverviewTrend, queryFn: dashboardService.getFinancialOverviewTrend });
  const { data: contributionsData = [] } = useQuery({ queryKey: queryKeys.dashboard.contributionsTrend, queryFn: dashboardService.getContributionsTrend });
  const { data: repaymentsData = [] } = useQuery({ queryKey: queryKeys.dashboard.repaymentsTrend, queryFn: dashboardService.getRepaymentsTrend });
  return <div className="grid gap-4 xl:grid-cols-[1.45fr_1fr]"><Panel title={t('dashboard', 'financialOverview')} icon={Landmark} className="min-w-0"><CardContent className="p-4 pt-5"><div className="mb-3 flex flex-wrap gap-4 text-[11px] text-muted-foreground">{overviewConfig.map((item) => <span key={item.key} className="flex items-center gap-1.5"><span aria-hidden="true" className="size-2 rounded-full" style={{ backgroundColor: item.color }} />{item.label}</span>)}</div>{financialOverviewData.length ? <div role="img" aria-label={t('dashboard', 'financialOverview')} className="h-[260px]"><ResponsiveContainer width="100%" height="100%"><AreaChart data={financialOverviewData} margin={{ top: 8, right: 8, left: -18, bottom: 0 }}><defs><linearGradient id="treasuryFill" x1="0" y1="0" x2="0" y2="1"><stop offset="5%" stopColor={chartColors.blue} stopOpacity={0.24} /><stop offset="95%" stopColor={chartColors.blue} stopOpacity={0} /></linearGradient></defs><CartesianGrid vertical={false} strokeDasharray="3 3" className="stroke-border/60" /><XAxis dataKey="month" axisLine={false} tickLine={false} tickMargin={8} /><YAxis axisLine={false} tickLine={false} tickFormatter={(value: number) => `${value}M`} /><Tooltip content={<ChartTooltipContent currencyLabel={currencyLabel} />} /><Area type="monotone" dataKey="treasury" name={t('dashboard', 'seriesTreasury')} stroke={chartColors.blue} strokeWidth={2.5} fill="url(#treasuryFill)" /><Line type="monotone" dataKey="contributions" name={t('dashboard', 'seriesContributions')} stroke={chartColors.green} strokeWidth={2} dot={false} /><Line type="monotone" dataKey="repayments" name={t('dashboard', 'seriesRepayments')} stroke={chartColors.amber} strokeWidth={2} dot={false} /></AreaChart></ResponsiveContainer></div> : <EmptyState icon={Landmark} title={t('dashboard', 'noData')} />}</CardContent></Panel><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-1"><SmallChart title={t('dashboard', 'contributionsChart')} icon={Coins} data={contributionsData} dataKey="contributions" targetKey="target" color={chartColors.green} t={t} /><SmallChart title={t('dashboard', 'repaymentsChart')} icon={HandCoins} data={repaymentsData} dataKey="repayments" targetKey="target" color={chartColors.amber} t={t} /></div></div>;
}

function SmallChart({ title, icon: Icon, data, dataKey, targetKey, color, t }: { title: string; icon: LucideIcon; data: Array<Record<string, number | string>>; dataKey: string; targetKey: string; color: string; t: T }) {
  const currencyLabel = getCurrencyDisplayLabel(useOrganizationCurrency());
  return <Panel title={title} icon={Icon}><CardContent className="p-3 pt-4">{data.length ? <div role="img" aria-label={title} className="h-[108px]"><ResponsiveContainer width="100%" height="100%"><BarChart data={data} margin={{ top: 4, right: 4, left: -28, bottom: -4 }}><CartesianGrid vertical={false} strokeDasharray="3 3" className="stroke-border/50" /><XAxis dataKey="month" axisLine={false} tickLine={false} tick={{ fontSize: 10 }} /><YAxis hide /><Tooltip content={<ChartTooltipContent currencyLabel={currencyLabel} />} /><Bar dataKey={targetKey} name={t('dashboard', 'seriesTarget')} fill={chartColors.slate} radius={[3, 3, 0, 0]} barSize={10} /><Bar dataKey={dataKey} name={title} fill={color} radius={[3, 3, 0, 0]} barSize={10} /></BarChart></ResponsiveContainer></div> : <EmptyState icon={Icon} title={t('dashboard', 'noData')} />}</CardContent></Panel>;
}

function LoanAndTontineCharts({ t, loansDistribution }: { t: T; loansDistribution: DashboardOverview['loansDistribution'] }) {
  const loanColors = [chartColors.blue, chartColors.amber, chartColors.green, chartColors.rose];
  const total = loansDistribution.reduce((sum, item) => sum + item.value, 0);
  const { data: tontineActivityData = [] } = useQuery({ queryKey: queryKeys.dashboard.tontineActivityTrend, queryFn: dashboardService.getTontineActivityTrend });
  return <div className="grid gap-4 lg:grid-cols-2"><Panel title={t('dashboard', 'loansChart')} icon={CreditCard}><CardContent className="grid items-center gap-4 p-4 pt-5 sm:grid-cols-[180px_1fr]">{total > 0 ? <div role="img" aria-label={t('dashboard', 'loansChart')} className="h-[180px]"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={loansDistribution} dataKey="value" nameKey="key" innerRadius={53} outerRadius={78} paddingAngle={3} strokeWidth={0}>{loansDistribution.map((entry, index) => <Cell key={entry.key} fill={loanColors[index]} />)}</Pie><Tooltip formatter={(value: number) => formatNumber(value)} /></PieChart></ResponsiveContainer></div> : <EmptyState icon={CreditCard} title={t('dashboard', 'noData')} />}<div className="space-y-3">{loansDistribution.map((item, index) => <div key={item.key} className="flex items-center justify-between gap-3 text-xs"><span className="flex items-center gap-2 text-muted-foreground"><span aria-hidden="true" className="size-2 rounded-full" style={{ backgroundColor: loanColors[index] }} />{t('dashboard', item.key)}</span><span className="font-semibold text-foreground">{formatNumber(item.value)}</span></div>)}<div className="mt-2 border-t border-border pt-2 text-xs"><span className="text-muted-foreground">{t('dashboard', 'totalLoans')}</span><span className="float-right font-semibold">{formatNumber(total)}</span></div></div></CardContent></Panel><Panel title={t('dashboard', 'tontineActivity')} icon={Coins}><CardContent className="p-4 pt-5"><div className="mb-3 flex gap-4 text-[11px] text-muted-foreground"><span className="flex items-center gap-1.5"><span aria-hidden="true" className="size-2 rounded-full bg-primary" />{t('dashboard', 'seriesOccurrences')}</span><span className="flex items-center gap-1.5"><span aria-hidden="true" className="size-2 rounded-full bg-emerald-500" />{t('dashboard', 'seriesParticipants')}</span></div>{tontineActivityData.length ? <div role="img" aria-label={t('dashboard', 'tontineActivity')} className="h-[190px]"><ResponsiveContainer width="100%" height="100%"><LineChart data={tontineActivityData} margin={{ top: 8, right: 8, left: -28, bottom: 0 }}><CartesianGrid vertical={false} strokeDasharray="3 3" className="stroke-border/50" /><XAxis dataKey="month" axisLine={false} tickLine={false} tick={{ fontSize: 10 }} /><YAxis axisLine={false} tickLine={false} tick={{ fontSize: 10 }} /><Tooltip content={<ChartTooltipContent money={false} />} /><Line type="monotone" dataKey="occurrences" name={t('dashboard', 'seriesOccurrences')} stroke={chartColors.blue} strokeWidth={2.5} dot={{ r: 3, fill: chartColors.blue }} /><Line type="monotone" dataKey="participants" name={t('dashboard', 'seriesParticipants')} stroke={chartColors.green} strokeWidth={2} dot={{ r: 3, fill: chartColors.green }} /></LineChart></ResponsiveContainer></div> : <EmptyState icon={Coins} title={t('dashboard', 'noData')} />}</CardContent></Panel></div>;
}

function RecentActivityWidget({ t, locale, items }: { t: T; locale: 'fr' | 'en'; items: DashboardOverview['recentActivity'] }) {
  return <Panel title={t('dashboard', 'recentActivity')} icon={Sparkles} action={<button type="button" aria-label={t('dashboard', 'moreOptions')} className="rounded-md p-1 text-muted-foreground hover:bg-muted"><MoreHorizontal size={16} /></button>}><CardContent className="p-4">{items.length ? <div className="space-y-4">{items.map((item) => <div key={item.id} className="flex gap-3"><span aria-hidden="true" className="mt-1 grid size-7 shrink-0 place-items-center rounded-full bg-primary/10 text-primary"><Sparkles size={13} /></span><div className="min-w-0 flex-1"><p className="text-xs leading-5"><span className="font-semibold">{item.label}</span><span className="text-muted-foreground"> · {t('dashboard', item.typeKey)}</span></p><p className="mt-0.5 text-[11px] text-muted-foreground">{formatDate(item.date, locale)}</p></div></div>)}</div> : <EmptyState icon={Sparkles} title={t('dashboard', 'noData')} />}</CardContent></Panel>;
}

function TransactionsWidget({ t, locale, items }: { t: T; locale: 'fr' | 'en'; items: DashboardOverview['recentTransactions'] }) {
  const currency = useOrganizationCurrency();
  return <Panel title={t('dashboard', 'recentTransactions')} icon={ReceiptText} action={<button type="button" className="text-[11px] font-semibold text-primary transition-colors hover:text-primary/70">{t('dashboard', 'viewAll')}</button>}><CardContent className="p-0">{items.length ? <div className="divide-y divide-border">{items.map((item) => <div key={item.id} className="flex items-center gap-3 px-4 py-3"><span aria-hidden="true" className="grid size-8 shrink-0 place-items-center rounded-lg bg-muted text-muted-foreground"><ReceiptText size={14} /></span><div className="min-w-0 flex-1"><p title={item.member} className="truncate text-xs font-semibold">{item.member}</p><p className="text-[11px] text-muted-foreground">{t('dashboard', item.typeKey)} · {formatDate(item.date, locale)}</p></div><div className="text-right"><p className="text-xs font-semibold">{formatCurrency(item.amount, currency, locale)}</p><StatusBadge label={t('dashboard', item.statusKey)} tone={item.statusKey === 'statusCompleted' ? 'success' : 'warning'} /></div></div>)}</div> : <div className="p-6"><EmptyState icon={ReceiptText} title={t('dashboard', 'noData')} /></div>}</CardContent></Panel>;
}

function UpcomingPaymentsWidget({ t, locale, items }: { t: T; locale: 'fr' | 'en'; items: DashboardOverview['upcomingPayments'] }) {
  const currency = useOrganizationCurrency();
  return <Panel title={t('dashboard', 'upcomingPayments')} icon={CalendarClock}><CardContent className="p-4">{items.length ? <div className="space-y-3">{items.map((item) => { const days = daysUntil(item.dueDate); return <div key={item.id} className="flex items-center gap-3"><div aria-hidden="true" className="grid size-8 shrink-0 place-items-center rounded-lg bg-amber-500/10 text-amber-600 dark:text-amber-400"><CalendarClock size={15} /></div><div className="min-w-0 flex-1"><p title={item.member} className="truncate text-xs font-semibold">{item.member}</p><p className="text-[11px] text-muted-foreground">{days <= 0 ? t('dashboard', 'today') : days === 1 ? t('dashboard', 'tomorrow') : t('dashboard', 'inDays', { days: String(days) })}</p></div><span className="text-xs font-semibold">{formatCurrency(item.amount, currency, locale)}</span></div>; })}</div> : <EmptyState icon={CalendarClock} title={t('dashboard', 'noData')} />}</CardContent></Panel>;
}

function LoanDueDatesWidget({ t, locale, items }: { t: T; locale: 'fr' | 'en'; items: DashboardOverview['loanDueDates'] }) {
  const currency = useOrganizationCurrency();
  return <Panel title={t('dashboard', 'loanDueDates')} icon={Clock3}><CardContent className="space-y-4 p-4">{items.length ? items.map((item) => <div key={item.id}><div className="mb-1.5 flex items-center justify-between gap-3"><div className="min-w-0"><p title={item.member} className="truncate text-xs font-semibold">{item.member}</p><p className="text-[10px] text-muted-foreground">{item.id} · {formatDate(item.dueDate, locale)}</p></div><span className="shrink-0 text-xs font-semibold">{formatCurrency(item.amount, currency, locale, { compact: true })}</span></div><Progress value={item.progress} className="h-1.5" aria-label={`${item.member} · ${t('dashboard', 'progress')}`} /></div>) : <EmptyState icon={Clock3} title={t('dashboard', 'noData')} />}</CardContent></Panel>;
}

function NotificationsWidget({ t, locale, items }: { t: T; locale: 'fr' | 'en'; items: DashboardOverview['importantNotifications'] }) {
  const priorityTone = { high: 'error' as const, medium: 'warning' as const, low: 'info' as const };
  const priorityKey = { high: 'priorityHigh', medium: 'priorityMedium', low: 'priorityLow' } as const;
  return <Panel title={t('dashboard', 'importantNotifications')} icon={BellRing}><CardContent className="p-4">{items.length ? <div className="space-y-3">{items.map((item) => <div key={item.id} className="flex gap-3"><span aria-hidden="true" className={`mt-1 size-2 shrink-0 rounded-full ${item.priority === 'high' ? 'bg-rose-500' : item.priority === 'medium' ? 'bg-amber-500' : 'bg-blue-500'}`} /><div className="min-w-0 flex-1"><div className="flex items-start justify-between gap-2"><p className="text-xs font-semibold">{t('notifications', item.titleKey)}</p><StatusBadge label={t('dashboard', priorityKey[item.priority])} tone={priorityTone[item.priority]} /></div><p title={`${item.detail} · ${formatDate(item.date, locale)}`} className="mt-0.5 truncate text-[11px] text-muted-foreground">{item.detail} · {formatDate(item.date, locale)}</p></div></div>)}</div> : <EmptyState icon={BellRing} title={t('dashboard', 'noData')} />}</CardContent></Panel>;
}

function ApprovalsWidget({ t, locale, items }: { t: T; locale: 'fr' | 'en'; items: DashboardOverview['pendingApprovals'] }) {
  const currency = useOrganizationCurrency();
  return <Panel title={t('dashboard', 'pendingApprovals')} icon={ClipboardCheck} action={<span aria-hidden="true" className="grid size-6 place-items-center rounded-full bg-amber-500/10 text-[11px] font-bold text-amber-600 dark:text-amber-400">{items.length}</span>}><CardContent className="p-4">{items.length ? <div className="space-y-2.5">{items.map((item) => <div key={item.id} className="flex items-center gap-2.5 rounded-lg border border-border/60 p-2.5"><span aria-hidden="true" className="grid size-8 shrink-0 place-items-center rounded-lg bg-muted text-muted-foreground"><ClipboardCheck size={14} /></span><div className="min-w-0 flex-1"><p title={t('dashboard', item.typeKey)} className="truncate text-xs font-semibold">{t('dashboard', item.typeKey)}</p><p title={`${item.requester} · ${formatDate(item.date, locale)}`} className="truncate text-[11px] text-muted-foreground">{item.requester} · {formatDate(item.date, locale)}</p></div>{item.amount > 0 && <span className="text-right text-[11px] font-semibold">{formatCurrency(item.amount, currency, locale, { compact: true })}</span>}<button type="button" aria-label={`${t('dashboard', 'review')} · ${t('dashboard', item.typeKey)}`} className="rounded-md p-1.5 text-primary hover:bg-primary/10"><ArrowUpRight size={14} /></button></div>)}</div> : <EmptyState icon={ClipboardCheck} title={t('dashboard', 'noData')} />}</CardContent></Panel>;
}

export function DashboardOverview() {
  const { t, locale } = useLocale();
  const { currentTenant } = useTenant();
  const typedLocale = locale as 'fr' | 'en';
  const greeting = useMemo(() => new Intl.DateTimeFormat(locale === 'en' ? 'en-US' : 'fr-FR', { weekday: 'long', day: 'numeric', month: 'long', year: 'numeric' }).format(new Date()), [locale]);
  const { data: overview, isLoading, isError, refetch } = useQuery({ queryKey: queryKeys.dashboard.overview(currentTenant.id), queryFn: () => dashboardService.getOverview(currentTenant.id) });
  if (isLoading) return <div className="mx-auto max-w-[1640px] space-y-5 p-5 sm:p-7"><CardSkeleton count={5} /><CardSkeleton count={3} /></div>;
  if (isError) return <div className="mx-auto max-w-[1640px] p-5 sm:p-7"><ErrorState onRetry={refetch} /></div>;
  if (!overview) return null;
  return <div className="mx-auto max-w-[1640px] p-5 sm:p-7"><div className="mb-6 flex flex-col justify-between gap-4 border-b border-border pb-6 md:flex-row md:items-end"><div><p className="mb-2 flex items-center gap-2 text-[11px] font-bold uppercase tracking-[.15em] text-primary"><Sparkles size={13} />{t('dashboard', 'eyebrow')}</p><h1 className="font-heading text-3xl font-semibold tracking-tight">{t('dashboard', 'title')}</h1><p className="mt-2 text-sm text-muted-foreground">{t('dashboard', 'description')} · {currentTenant.name}</p></div><div className="flex items-center gap-2 text-xs text-muted-foreground"><CalendarClock size={14} />{greeting}</div></div><div className="space-y-5"><KpiGrid t={t} locale={typedLocale} kpis={overview.kpis} /><FinancialCharts t={t} /><LoanAndTontineCharts t={t} loansDistribution={overview.loansDistribution} /><div className="grid gap-4 xl:grid-cols-2"><RecentActivityWidget t={t} locale={typedLocale} items={overview.recentActivity} /><TransactionsWidget t={t} locale={typedLocale} items={overview.recentTransactions} /></div><div className="grid gap-4 md:grid-cols-2"><UpcomingPaymentsWidget t={t} locale={typedLocale} items={overview.upcomingPayments} /><LoanDueDatesWidget t={t} locale={typedLocale} items={overview.loanDueDates} /></div><div className="grid gap-4 xl:grid-cols-2"><NotificationsWidget t={t} locale={typedLocale} items={overview.importantNotifications} /><ApprovalsWidget t={t} locale={typedLocale} items={overview.pendingApprovals} /></div></div></div>;
}
